// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQUSp7NzGwD7j6-IFqdd2kWUMi0Og5Ns',
    appId: '1:346739983731:web:55ad6d61d119ec1fbcb106',
    messagingSenderId: '346739983731',
    projectId: 'fireeeee-4b515',
    authDomain: 'fireeeee-4b515.firebaseapp.com',
    databaseURL: 'https://fireeeee-4b515-default-rtdb.firebaseio.com',
    storageBucket: 'fireeeee-4b515.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwcAOFZ6yhnJUIZqjSSSYrEtyEOVU6pM',
    appId: '1:346739983731:android:7dd624b484f5b069bcb106',
    messagingSenderId: '346739983731',
    projectId: 'fireeeee-4b515',
    databaseURL: 'https://fireeeee-4b515-default-rtdb.firebaseio.com',
    storageBucket: 'fireeeee-4b515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWnNDjg7iy9UyliiLpElU-sUSW--g92o',
    appId: '1:346739983731:ios:db3e55e30562379cbcb106',
    messagingSenderId: '346739983731',
    projectId: 'fireeeee-4b515',
    databaseURL: 'https://fireeeee-4b515-default-rtdb.firebaseio.com',
    storageBucket: 'fireeeee-4b515.appspot.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbWnNDjg7iy9UyliiLpElU-sUSW--g92o',
    appId: '1:346739983731:ios:ee5932bf43a9c85bbcb106',
    messagingSenderId: '346739983731',
    projectId: 'fireeeee-4b515',
    databaseURL: 'https://fireeeee-4b515-default-rtdb.firebaseio.com',
    storageBucket: 'fireeeee-4b515.appspot.com',
    iosBundleId: 'com.example.fireapp.RunnerTests',
  );
}
